name: Download-anything

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
 TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initialization environment
      id: init
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"

    - name: Clone source code
      run: |
       curl https://storage.googleapis.com/git-repo-downloads/repo -o repo
       chmod +x repo
       ./repo init -u git://source.codeaurora.org/quic/cc-qrdk/releases/manifest/qstak -b release -m caf_AU_LINUX_QSDK_NHSS.QSDK.11.5.0.4.R7_TARGET_ALL.11.5.0407.7984.005.xml
       ls
       ./repo sync
       ls

    - name: Achieve
      id: achieve
      run: |
       cd ..
       mkdir packup
       tar -czf packup/qsdk-11.5.04.tar.gz /home/runner/work/test1/test1/*

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      with:
        name: qsdk-11.5.04
        path: /home/runner/work/test1/packup


#Alternatively
#caf_AU_LINUX_QSDK_NHSS.QSDK.11.4_TARGET_ALL.12.0.6938.000.6969.xml
#caf_AU_LINUX_QSDK_NHSS.QSDK.11.3_TARGET_ALL.12.0.5871.00.6204.xml
#caf_AU_LINUX_QSDK_NHSS.QSDK.11.2_TARGET_ALL.12.0.4959.5165.xml
#caf_AU_LINUX_QSDK_NHSS.QSDK.11.1_TARGET_ALL.12.0.4170.001.5167.xml
#caf_AU_LINUX_QSDK_NHSS.QSDK.11.1.R1_TARGET_ALL.12.0.4093.004.xml
#caf_AU_LINUX_QSDK_NHSS.QSDK.11.0_TARGET_ALL.11.0.3821.4517.xml
#caf_AU_LINUX_QSDK_NHSS.QSDK.11.5.0.5.R7_TARGET_ALL.12.0.000.934.009.xml
#caf_AU_LINUX_QSDK_NHSS.QSDK.12.1.R2_TARGET_ALL.12.1.02.841.013.xml
#caf_AU_LINUX_QSDK_NHSS.QSDK.11.5.0.6_TARGET_ALL.11.5.0.6.055.xml
#caf_AU_LINUX_QSDK_NHSS.QSDK_XR.1.0_TARGET_ALL.000.025.xml
